# Generated by Django 4.0.1 on 2022-11-25 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fs', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=500)),
                ('date_pat', models.CharField(max_length=100)),
                ('news_pat', models.CharField(max_length=100)),
                ('short_exp', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('news', models.CharField(max_length=500)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fsupdater.entity')),
            ],
        ),
    ]
